package gameEngine.objects;

import gameEngine.Character;
import gameEngine.MainEngine;
import gameEngine.tools.Coordinates;

import java.awt.image.BufferedImage;
import java.util.ArrayList;

/**
 * interface that represents a miscellaneous object on the map and its
 * properties e.g., crates, walls, mines
 * 
 *
 */
public interface MiscObject {
	
	/**
	 * Get the current coordinates of the object
	 * @return
	 */
	public Coordinates getCurrCoord();

	/**
	 * Set the current coordinates of the object
	 * @param currCoord
	 */
	public void setCurrCoord(Coordinates currCoord);

	/**
	 * Read the display image of the object
	 * @param path
	 */
	public void readImg(String path);

	/**
	 * Get the display image of the object
	 * @return
	 */
	public BufferedImage getDisplaySprite();

	/**
	 * Set the display image to something else
	 * @param displaySprite
	 */
	public void setDisplaySprite(BufferedImage displaySprite);

	/**
	 * Get the HP of the item
	 * @return
	 */
	public int getHp();

	/**
	 * Set the hp of the item
	 * @param hp
	 */
	public void setHp(int hp);

	/**
	 * Get the type of this object
	 * @return
	 */
	public String getObjectType();

	/**
	 * Get all the coordinates of the object - used for collision detection
	 * @return
	 */
	public ArrayList<Coordinates> getAllCoordinates();
	
	/**
	 * Updates game state after player interacts with object
	 * @param activeCharacter
	 * @param engine
	 * @return
	 */
	public int updateAfterCrate(Character activeCharacter , MainEngine engine);

	/**
	 * Gets the last update string generated by this object
	 * @return
	 */
	public String getLastUpdate();

	/**
	 * Get the width of the object
	 * @return
	 */
	public int getWidth();

	/**
	 * Get the height of the object
	 * @return
	 */
	public int getHeight();

}
