/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-12-09 22:43:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DataBase_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>PhoneBook</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"view.css\" media=\"all\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"view.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"main_body\" >\r\n");
      out.write("\t\r\n");
      out.write("\t<img id=\"top\" src=\"top.png\" alt=\"\">\r\n");
      out.write("\t<div id=\"form_container\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h1><a>PhoneBook</a></h1>\r\n");
      out.write("\t\t<form id=\"form_941990\" class=\"appnitro\"  method=\"post\" action=\"ControllerDataBase\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form_description\">\r\n");
      out.write("\t\t\t<h2>PhoneBook</h2>\r\n");
      out.write("\t\t\t<p>Add and Search</p>\r\n");
      out.write("\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<ul >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<li id=\"li_1\" >\r\n");
      out.write("\t\t<label class=\"description\" for=\"searchFirstField\">Search name </label>\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<input id=\"searchFirstField\" name= \"searchFirstField\" class=\"element text\" maxlength=\"255\" size=\"8\" value=\"\"/>\r\n");
      out.write("\t\t\t<label>First</label>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<input id=\"searchLastField\" name= \"searchLastField\" class=\"element text\" maxlength=\"255\" size=\"14\" value=\"\"/>\r\n");
      out.write("\t\t\t<label>Last</label>\r\n");
      out.write("\t\t</span> \r\n");
      out.write("\t\t</li>\t\t<li id=\"li_2\" >\r\n");
      out.write("\t\t<label class=\"description\" for=\"searchEmailField\">Search Email </label>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input id=\"searchEmailField\" name=\"searchEmailField\" class=\"element text medium\" type=\"text\" maxlength=\"255\" value=\"\"/> \r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t</li>\t\t<li id=\"li_3\" >\r\n");
      out.write("\t\t<label class=\"description\" for=\"addFirstField\">Add Name </label>\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<input id=\"addFirstField\" name= \"addFirstField\" class=\"element text\" maxlength=\"255\" size=\"8\" value=\"\"/>\r\n");
      out.write("\t\t\t<label>First</label>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<span>\r\n");
      out.write("\t\t\t<input id=\"addLastField\" name= \"addLastField\" class=\"element text\" maxlength=\"255\" size=\"14\" value=\"\"/>\r\n");
      out.write("\t\t\t<label>Last</label>\r\n");
      out.write("\t\t</span> \r\n");
      out.write("\t\t</li>\t\t<li id=\"li_4\" >\r\n");
      out.write("\t\t<label class=\"description\" for=\"addEmailField\">Add Email </label>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input id=\"addEmailField\" name=\"addEmailField\" class=\"element text medium\" type=\"text\" maxlength=\"255\" value=\"\"/> \r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"buttons\">\r\n");
      out.write("\t\t\t    <input type=\"hidden\" name=\"form_id\" value=\"941990\" />\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t<input id=\"saveForm\" class=\"button_text\" type=\"submit\" name=\"button1\" value=\"Search Contact\" />\r\n");
      out.write("\t\t\t\t<input id=\"saveForm\" class=\"button_text\" type=\"submit\" name=\"button2\" value=\"Add Contact\" />\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<img id=\"bottom\" src=\"bottom.png\" alt=\"\">\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
